# Generated by Django 5.2.7 on 2025-12-10 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0002_remove_order_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
