# Generated by Django 5.2.7 on 2025-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("point_of_sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="properties",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="point_of_sale.property"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
