# Generated by Django 5.2.7 on 2025-12-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number_tables", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.PositiveIntegerField()),
                ("max_guests_num", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True, related_name="tables", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables",
                        to="point_of_sale.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "table_number"),
                        name="unique_table_per_property",
                    )
                ],
            },
        ),
    ]
