# Generated by Django 5.2.7 on 2025-12-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["table_number"]},
        ),
    ]
