# Generated by Django 5.2.7 on 2025-12-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0002_alter_table_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="employees",
        ),
    ]
