# Generated by Django 5.2.7 on 2025-12-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["name"]},
        ),
    ]
